# Generated by Django 5.2.15 on 2026-06-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='custom_css',
            field=models.TextField(blank=True, null=True, verbose_name='Кастомный CSS'),
        ),
    ]
