# Generated by Django 5.2.15 on 2026-06-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_shop_custom_css'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='custom_css',
        ),
        migrations.AddField(
            model_name='shop',
            name='design_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Конфигурация дизайна'),
        ),
    ]
